### PR TITLE
Feature/lsf refactor

### PR DESCRIPTION
**Pull request by JamesCreamer**
Enable users to work with parallel LSF processes by overriding the git init and shutdown

### CODE REVIEW

**Comment by priyavadan** [comment]
Thao has confirmed that the branch worked for NXP/nvm folks without any changes. I suspect no one apart from them is actually using this plugin 

@chrisnappi @coreyeng, is that correct?

**Comment by pderouen** [comment]
@priyavadan, we're not using it on our side.

**Review by priyavadan — APPROVED** [review]

**Review by coreyeng — APPROVED** [review]
I think we had some stuff that tried to use it but didn't end up doing much. Looks like its mostly "additions" rather than "changes to existed stuff" anyway and if it works for NVM its very likely fine for us.

**Comment by priyavadan** [comment]
@redxeth any concerns?

**Comment by redxeth** [comment]
@priyavadan I think if @ThaoHuynhFsl  is ok then i'm ok.  He's using it more than me.

**Comment by priyavadan** [comment]
Will merge! Thanks for the support folks!

**Pull request merged**
