### PR TITLE
Bug fixes and internal overhaul  **Breaking Change!**

### PR DESCRIPTION
**Pull request by ginty**
This PR fixes a number of bugs and significantly improves and simplifies the internal allocation logic.

It is a breaking change because the bin, softbin, etc. are now no longer passed into callback functions directly, but instead are included in a common options hash that is now passed to all callbacks.

The previous implementation imposed special handling of bins vs. softbins vs. test numbers which significantly complicated the implementation, introduced many corner cases to think about, and generally placed restrictions on how callbacks could be used within applications.
With the new implementation, all 3 number types are treated the same, the can all use callbacks (previously bins could not) and they can depend on each however the application requires.

To update an application, this:

~~~ruby
config.softbins do |bin|
  bin * 5
end
~~~

should change to this:

~~~ruby
config.softbins needs: :bin do |options|
  options[:bin] * 5
end
~~~

All other APIs remain the same.

Here is a summary of the feature additions and bug fixes:

* Leading counter fields in algorithms did not work, but should be a valid thing to do per the spec, this fixes it:

  ~~~ruby
  TestIds.configure do |config|
    config.bins.include << 3
    config.softbins.include << 2000
    config.numbers = "xxxssss"
  end

  a(:t0)[:number].should == 2000
  a(:t1)[:number].should == 12000
  a(:t2)[:number].should == 22000
  a(:t3)[:number].should == 32000
  a(:t2)[:number].should == 22000
  ~~~

* Previously the internal pointers when working through an include range did not take account of a (increment step) size being > 1. This created the corner case bug where if the last test had a size > 1, the full span of the allocation would not be reserved when it started up again next time.

* Bins, softbins, and numbers can now all depend on each other and be assigned from a range, algorithm or callback (previously the bin could only be from a range). For algorithms, TestIds will automatically work out the correct generation order, for callbacks, the user should help by supplying needs information as shown in the above example.

* A configuration no longer has to define bins, softbins and numbers, it can only define the ones it cares about. While not specifically tested, the fact that it happily handles an empty bin configuration should fix this bug - https://github.com/Origen-SDK/test_ids/issues/13

* Convenience methods `TestIds.allocate_bin`, `TestIds.allocate_softbin` and `TestIds.allocate_number` have been added for where the application wants only one of these to be generated.

* Added improved support for multi-configuration setups, see here for info - https://github.com/Origen-SDK/test_ids/tree/5949de3651cdbd9365b2d5bee678eb1849a585f9#multiple-active-configurations

* The documentation has been fully updated to reflect all of the above

### CODE REVIEW

**Review by info-rchitect — COMMENTED** [review]
@ginty What caused the bug where `bin: :none` on the first test caused a problem?

**Comment by ginty** [comment]
@info-rchitect  ?

**Comment by info-rchitect** [comment]
@ginty was this PR related in part to [this issue](https://github.com/Origen-SDK/test_ids/issues/13)?

**Comment by ginty** [comment]
nope

**Review by priyavadan — APPROVED** [review]
LGTM! Thanks!

**Comment by ginty** [comment]
@info-rchitect, FYI these updates are turning into more of a general overhaul to fix a few issues I have come up against recently and I'm pretty sure it will fix whatever the root cause of your issue was.
Will update this overview when complete with the changes.

**Comment by info-rchitect** [comment]
@ginty thx for the head's up.  I appreciate all of the efforts as this gem is very helpful.

**Comment by ginty** [comment]
@priyavadan, @info-rchitect please re-review.
@rlaj, please confirm if you are happy with this since it is breaking.
Thanks!

**Comment by priyavadan** [comment]
@ginty thanks for the overhaul! Since my use case is a part of the specs, I am fairly confident this should be okay. 

I would still like to update my app to use these changes and confirm, would Monday be okay to give you feedback by , if this breaks anything?

**Comment by ginty** [comment]
@priyavadan, yes, no problem

**Comment by info-rchitect** [comment]
@ginty I took the same configuration I had before:

~~~ruby
TestIds.configure :ws1 do |config|
  config.bins.include << (5..16)
  config.softbins.algorithm = :bbxxx
~~~

In this case, I pass in the bin in the flow file and let TestIds assign a matching softbin using the algorithm.

~~~ruby
scan :chain, bin: 11 # Not showing all of the test metadata passed for brevity
~~~

Here is what I used to get in our binning XML file:

~~~xml
    <HardBin id="11" desc="SCAN_CHAIN" passfail="F">
      <SoftBins>
        <SoftBin id="11000" desc="scan_chain_micintest0_na_0cyc_vmin_uncomp_11000" />
        <SoftBin id="11001" desc="scan_chain_micintest0_na_0cyc_vmin_11001" />
        <SoftBin id="11002" desc="scan_chain_micintest1_na_0cyc_vmin_uncomp_11002" />
        <SoftBin id="11003" desc="scan_chain_micintest1_na_0cyc_vmin_11003" />
        <SoftBin id="11004" desc="scan_chain_micintest3_na_0cyc_vmin_uncomp_11004" />
        <SoftBin id="11005" desc="scan_chain_micintest3_na_0cyc_vmin_11005" />
        <SoftBin id="11006" desc="scan_chain_micintest2_na_0cyc_vmin_uncomp_11006" />
        <SoftBin id="11007" desc="scan_chain_micintest2_na_0cyc_vmin_11007" />
        <SoftBin id="11008" desc="scan_chain_micintest5_na_0cyc_vmin_uncomp_11008" />
~~~

Here is what I get now.

~~~xml
    <HardBin id="11" desc="SCAN_CHAIN" passfail="F">
      <SoftBins>
        <SoftBin id="7000" desc="scan_chain_micintest0_na_0cyc_vmin_uncomp_7000" />
        <SoftBin id="8000" desc="scan_chain_micintest0_na_0cyc_vmin_8000" />
        <SoftBin id="9000" desc="scan_chain_micintest1_na_0cyc_vmin_uncomp_9000" />
        <SoftBin id="10000" desc="scan_chain_micintest1_na_0cyc_vmin_10000" />
        <SoftBin id="12000" desc="scan_chain_micintest3_na_0cyc_vmin_uncomp_12000" />
        <SoftBin id="13000" desc="scan_chain_micintest3_na_0cyc_vmin_13000" />
        <SoftBin id="14000" desc="scan_chain_micintest2_na_0cyc_vmin_uncomp_14000" />
        <SoftBin id="15000" desc="scan_chain_micintest2_na_0cyc_vmin_15000" />
        <SoftBin id="11076" desc="scan_chain_micintest5_na_0cyc_vmin_uncomp_11076" />
~~~

Not sure it is working as expected.

**Comment by ginty** [comment]
Thanks @info-rchitect, that was a bug not covered by existing test cases.

I've added a new test case based on your example and it seems to be working now, please retry and feedback. Thanks!

**Comment by ginty** [comment]
@info-rchitect, as an aside, it was probably required under the old internal architecture, but with this new version you don't need to define `config.bins` at all if you are always going to pass it in from the flow file.

**Comment by ginty** [comment]
@info-rchitect, I also added here better support for multiple active configurations, see this doc update - https://github.com/Origen-SDK/test_ids/tree/5949de3651cdbd9365b2d5bee678eb1849a585f9#multiple-active-configurations

From some previous StackOverflow exchanges I got the impression that you might find this useful.

As far as allocation bin/softbin/number for different configs at the same time, I can imagine there could be some bugs there when that is put through its paces, so please report back if you try it and see any problems.

**Comment by info-rchitect** [comment]
@ginty I tested out the latest build and it is working with my test case where I pass in the bin from the flow file.  This is not the standard way we do things, usually each test module gets a bin defined in the config but for some test modules there are multiple bins based on the type of test being executed.

I like the configuration flexibility features for sure, will take a little time to digest them all and how we would use it.  But given the new features, how would you handle setting the hardbin based on a type of test (ATPG chain, stuck-at, delay for example)?

**Comment by ginty** [comment]
Thanks @info-rchitect.

I would say the way to do that is to assign the `:bin` option in your test flow to an identifier, rather than a hardcoded bin value:

~~~ruby
test :my_test_1, bin: :atpg_sa

test :my_test_2, bin: :atpg_sa

test :my_test_3, bin: :atpg_dly
~~~

When you assign a symbol to the `:bin`, `:softbin` or `:number` keys, then that will be used to identify the test for the purposes of assigning that type of number, instead of the test name.
Therefore, as far as TestIds is concerned, tests 1 and 2 in the above example are the same and they will be assigned to the same bin number.

You can let TestIds pick the number to be assigned from a range:

~~~ruby
config.bins.include << (10..20)
~~~

I'm not sure if the original bin option value will get passed into a callback currently, but with this update it would not take much effort to add support something like this in your application logic if you prefer:

~~~ruby
config.bins do |options|
  case options[:bin]
  when :atpg_sa
     10
  when :atpg_dly
     11
  else
     fail "Unknown bin identifier: #{options[:bin]}"
  end
end
~~~

**Comment by priyavadan** [comment]
Looks good to me. Updated configuration in the application to work with this new change. Output compares! Thanks!

**Comment by ginty** [comment]
thanks @priyavadan

**Comment by info-rchitect** [comment]
@ginty i checked this and it works for us, can we merge?

**Comment by ginty** [comment]
@info-rchitect, done, v1.0.0 available now

**Comment by info-rchitect** [comment]
@ginty thx much, we are now going to find some of our most complicated binning use cases and stress test the gem.

**Pull request merged**
