### PR TITLE
extract test name only uses the test_id to extract the name

### PR DESCRIPTION
**Pull request by priyavadan**
@ginty does this change look okay to you? 

If I am passing the test name in the options, I still want the ability to use the instance name to be stored in the database,  if it is available.

### CODE REVIEW

**Comment by priyavadan** [comment]
origen specs is passing

Finished in 0.0232 seconds (files took 0.34312 seconds to load)
46 examples, 0 failures

**Review by ginty — CHANGES_REQUESTED** [review]
Seems like a breaking change to me, not sure what problem it is trying to solve or the justification...

**Comment by priyavadan** [comment]
The test name for the instance is always passed and thus the plug in always uses the test name to store the tnum, HBIN and SBIN in the database. We currently plan on adding a test flow index to the test name, so the test name will change everytime a new test is inserted within the flow. The requirement for the app is to tie the test instance name with the tnum, sbin and hardbin.

I understand this might be a breaking change. Also looks like the internal requirements have changed slightly so I am currently re-evaluating, however the capability to create/store/query the database that this plugin provides is something I would still like to use.

**Comment by ginty** [comment]
Seems like you should be able to do what you want easily enough at application-level without having to change anything here:

~~~ruby
options[:test_id] = my_instance.name
~~~

**Comment by priyavadan** [comment]
Makes sense, will close

**Pull request closed without merging**
